.TH CHR 1
.nh .\" Disable hyphenation
.ad l .\" Disable justification: left-align only
.SH NAME
\fBfilesafe\fP \-\- Replace unsafe filename characters with similar substitutes
.SH SYNOPSIS
\fBfilesafe\fP [\fI...strings\fP]
.SH DESCRIPTION
\fBfilesafe\fP replaces unsafe filename characters with similar-looking substitutes to fool the reader.
.PP
If no arguments are provided, the program reads from standard input.
.PP
The exact replacements performed are:
.nf
.IP \.\.\.
.B "    U+2026 HORIZONTAL ELLIPSIS"
.IP ?!
.B "    U+2048 QUESTION EXCLAMATION MARK"
.IP ??
.B "    U+2047 DOUBLE QUESTION MARK"
.IP /
.B "    U+2215 DIVISION SLASH"
.IP :
.B "    U+A789 MODIFIER LETTER COLON"
.IP """"""
.B "    U+201C LEFT DOUBLE QUOTATION MARK"
.B "    U+201D RIGHT DOUBLE QUOTATION MARK"
.IP <
.B "    U+FE64 SMALL LESS-THAN SIGN"
.IP >
.B "    U+FE65 SMALL GREATER-THAN SIGN"
.IP \.
.B "    U+2024 ONE DOT LEADER" *
.fi
.PP
* Only replaced if it's the last characcter in a string: directories can't end in full\-stops.
.SH AUTHOR
Copyright (c) 2016 John Gardner <\fIgardnerjohng@gmail.com\fP>.
.PP
Freely released under the ISC license. See also \fIhttp://opensource.org/licenses/ISC\fP.
